DROP TABLE item_cost;

-- Create the table
CREATE TABLE item_cost (
    item_name TEXT PRIMARY KEY,
    price INTEGER,
    rarity TEXT, 
    consumable INTEGER
);

-- Insert the data
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("+1 Shield", 1500, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("+2 Shield", 6000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("+3 Shield", 24000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Alchemy Jug", 6000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ammunition +1 (each)", 25, "uncommon", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ammunition +2 (each)", 100, "rare", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ammunition +3 (each)", 400, "very rare", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Amulet of Health", 8000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Amulet of Proof Against Detection and Location", 20000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Amulet of the Planes", 160000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Animated Shield", 6000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Apparatus of Kwalish", 10000, "legendary", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Arrow of Slaying (each)", 600, "very rare", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Arrow-Catching Shield", 6000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Bag of Holding", 4000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Bead of Force", 960, "rare", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Belt of Dwarvenkind", 6000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Boots of Elvenkind", 2500, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Boots of Levitation", 4000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Boots of Speed", 4000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Boots of Striding and Springing", 5000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Boots of the Winterlands", 10000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Bowl of Commanding Water Elementals", 8000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Bracers of Archery", 1500, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Bracers of Defense", 6000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Brass Horn of Valhalla", 8400, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Brazier of Commanding Fire Elementals", 8000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Bronze Griffon", 8000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Bronze Horn of Valhalla", 11200, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Brooch of Shielding", 7500, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Broom of Flying", 8000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Cap of Water Breathing", 1000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Cape of the Mountebank", 8000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Carpet of Flying", 12000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Censer of Controlling Air Elementals", 8000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Chime of Opening", 1500, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Circlet of Blasting", 1500, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Cloak of Arachnida", 5000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Cloak of Displacement", 60000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Cloak of Elvenkind", 5000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Cloak of Invisibility", 80000, "legendary", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Cloak of Protection", 3500, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Cloak of the Bat", 6000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Cloak of the Manta Ray", 6000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Crystal Ball", 50000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Cube of Force", 16000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Cubic Gate", 40000, "legendary", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Daern's Instant Fortress", 75000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Dagger of Venom", 2500, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Decanter of Endless Water", 135000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Deck of Illusions", 6120, "uncommon", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Dimensional Shackles", 3000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Dragon Scale Mail", 4000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Driftglobe", 750, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Dust of Disappearance", 300, "uncommon", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Dust of Dryness (1 pellet)", 120, "uncommon", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Dust of Sneezing and Choking", 480, "uncommon", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Dwarven Plate", 9000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Dwarven Thrower", 18000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ebony Fly", 6000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Efreeti Chain", 20000, "legendary", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Elemental Gem", 960, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Elixir of Health", 120, "rare", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Elven Chain", 4000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Eversmoking Bottle", 1000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Eyes of Charming", 3000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Eyes of Minute Seeing", 2500, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Eyes of the Eagle", 2500, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Folding Boat", 10000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Gauntlets of Ogre Power", 8000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Gem of Brightness", 5000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Gem of Seeing", 32000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Glamoured Studded Leather", 2000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Gloves of Missile Snaring", 3000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Gloves of Swimming and Climbing", 2000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Gloves of Thievery", 5000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Goggles of Night", 1500, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Golden Lion (each)", 600, "rare", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Hammer of Thunderbolts", 16000, "legendary", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Hat of Disguise", 5000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Headband of Intellect", 8000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Helm of Comprehend Languages", 500, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Helm of Telepathy", 12000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Helm of Teleportation", 64000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Heward's Handy Haversack", 2000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Horn of Blasting", 450, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Horseshoes of Speed", 5000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Horseshoes of the Zephyr", 1500, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Immovable Rod", 5000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Instrument of the Bards - Anstruth Harp", 109000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Instrument of the Bards - Canaith Mandolin", 30000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Instrument of the Bards - Cli Lyre", 35000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Instrument of the Bards - Doss Lute", 28500, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Instrument of the Bards - Fochulan Bandlore", 26500, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Instrument of the Bards - Mac-Fuirmidh Cittern", 27000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Instrument of the Bards - Ollamh Harp", 125000, "legendary", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ioun Stone of Absorption", 2400, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ioun Stone of Agility", 3000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ioun Stone of Awareness", 12000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ioun Stone of Fortitude", 3000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ioun Stone Greater Absorption", 31000, "legendary", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ioun Stone of Insight", 3000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ioun Stone of Intellect", 3000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ioun Stone of Leadership", 3000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ioun Stone of Mastery", 15000, "legendary", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ioun Stone of Protection", 1200, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ioun Stone of Regeneration", 4000, "legendary", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ioun Stone of Reserve", 6000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ioun Stone of Strength", 3000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ioun Stone of Sustenance", 1000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Iron Bands of Bilarro", 4000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Iron Horn of Valhalla", 14000, "legendary", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ivory Goat (Terror)", 20000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ivory Goat (Travail)", 400, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ivory Goat (Traveling)", 1000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Javelin of Lightning", 1500, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Keoghtoms Ointment (Per Dose)", 120, "uncommon", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Lantern of Revealing", 5000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Luckstone", 4200, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Mace of Disruption", 8000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Mace of Smiting", 7000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Mace of Terror", 8000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Mantle of Spell Resistance", 30000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Marble Elephant", 6000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Medallion of Thoughts", 3000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Mirror of Life Trapping", 18000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Necklace of Adaption", 1500, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Necklace of Fireballs (6 Beads)", 7680, "rare", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Necklace of Fireballs (5 Beads)", 3840, "rare", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Necklace of Fireballs (4 Beads)", 1600, "rare", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Necklace of Fireballs (3 Beads)", 960, "rare", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Necklace of Fireballs (2 Beads)", 480, "rare", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Necklace of Fireballs (1 Beads)", 300, "rare", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Nolzur's Marvelous Pigments", 200, "very rare", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Oathbow", 3500, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Obsidian Steed", 128000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Oil of Etherealness", 1920, "rare", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Oil of Sharpness", 3200, "very rare", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Oil of Slipperiness", 480, "uncommon", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Onyx Dog", 3000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Pearl of Power", 6000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Periapt of Health", 5000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Periapt of Proof Against Poison", 5000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Periapt of Wound Closure", 5000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Philter of Love", 90, "uncommon", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Pipes of Haunting", 6000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Pipes of the Sewers", 2000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Plate Armor of Etherealness", 48000, "legendary", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Portable Hole", 8000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Potion of Animal Friendship", 200, "uncommon", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Potion of Clairvoyance", 960, "rare", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Potion of Climbing", 180, "common", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Potion of Diminution", 270, "rare", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Potion of Fire Breath", 150, "uncommon", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Potion of Flying", 500, "very rare", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Potion of Gaseous Form", 300, "rare", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Potion of Greater Healing", 150, "uncommon", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Potion of Growth", 270, "uncommon", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Potion of Healing", 50, "common", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Potion of Heroism", 180, "rare", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Potion of Invisibility", 180, "very rare", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Potion of Invulnerability", 3840, "rare", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Potion of Longevity", 9000, "very rare", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Potion of Mind Reading", 180, "rare", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Potion of Poison", 100, "uncommon", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Potion of Resistance", 300, "uncommon", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Potion of Speed", 400, "very rare", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Potion of Superior Healing", 450, "rare", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Potion of Supreme Healing", 1350, "very rare", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Potion of Vitality", 960, "very rare", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Potion of Water Breathing", 180, "uncommon", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Prayer Bead - Bless", 2000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Prayer Bead - Curing", 4000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Prayer Bead - Favor", 32000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Prayer Bead - Smiting", 1500, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Prayer Bead - Summons", 128000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Prayer Bead - Wind Walking", 96000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Quaal's Feather Token Anchor", 50, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Quaal's Feather Token Bird", 3000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Quaal's Feather Token Fan", 250, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Quaal's Feather Token Swan Boat", 3000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Quaal's Feather Token Whip", 250, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Quiver of Ehlonna", 1000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ring of Air Elemental Command", 35000, "legendary", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ring of Animal Influence", 4000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ring of Earth Elemental Command", 31000, "legendary", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ring of Evasion", 5000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ring of Feather Falling", 2000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ring of Fire Elemental Command", 17000, "legendary", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ring of Free Action", 20000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ring of Invisibility", 10000, "legendary", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ring of Jumping", 2500, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ring of Mind Shielding", 16000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ring of Protection", 3500, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ring of Regeneration", 12000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ring of Resistance", 6000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ring of Shooting Stars", 14000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ring of Spell Storing", 24000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ring of Spell Turning", 30000, "legendary", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ring of Swimming", 3000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ring of Telekinesis", 80000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ring of the Ram", 5000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ring of Warmth", 1000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ring of Water Elemental Command", 25000, "legendary", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ring of Water Walking", 1500, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Ring of X-Ray Vision", 6000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Robe of Eyes", 30000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Robe of Scintillating Colors", 6000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Robe of Stars", 60000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Robe of the Archmagi", 34000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Rod of Absorption", 50000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Rod of Alertness", 25000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Rod of Lordly Might", 28000, "legendary", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Rod of Rulership", 16000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Rod of Security", 90000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Rod of the Pact Keeper +1", 12000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Rod of the Pact Keeper +2", 16000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Rod of the Pact Keeper +3", 28000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Amulet of the Devout +1", 12000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Amulet of the Devout +2", 16000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Amulet of the Devout +3", 28000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Bloodwell Vial +1", 12000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Bloodwell Vial +2", 16000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Bloodwell Vial +3", 28000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Arcane Grimoire +1", 12000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Arcane Grimoire +2", 16000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Arcane Grimoire +3", 28000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Moon Sickle +1", 12000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Moon Sickle +2", 16000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Moon Sickle +3", 28000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Rhythm Maker's Drum +1", 12000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Rhythm Maker's Drum +2", 16000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Rhythm Maker's Drum +3", 28000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("All-Purpose Tool +1", 12000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("All-Purpose Tool +2", 16000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("All-Purpose Tool +3", 28000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Dragonhide Belt +1", 12000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Dragonhide Belt +2", 16000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Dragonhide Belt +3", 28000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Rope of Climbing", 2000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Rope of Entanglement", 4000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Saddle of the Cavalier", 2000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Scarab of Protection", 36000, "legendary", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Scimitar of Speed", 6000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Scroll of Protection", 180, "rare", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Sending Stones", 2000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Sentinel Shield", 20000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Serpentine Owl", 8000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Shield of Missile Attraction", 6000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Silver Horn of Valhalla", 5600, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Silver Raven", 5000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Slippers of Spider Climbing", 5000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Sovereign Glue", 400, "legendary", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Spellguard Shield", 50000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Sphere of Annihilation", 15000, "legendary", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Staff of Charming", 12000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Staff of Fire", 16000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Staff of Frost", 26000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Staff of Healing", 13000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Staff of Power", 95500, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Staff of Striking", 21000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Staff of Swarming Insects", 16000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Staff of the Adder", 1800, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Staff of the Python", 2000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Staff of the Woodlands", 44000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Staff of Thunder and Lightning", 10000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Staff of Withering", 3000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Stone of Controlling Earth Elementals", 8000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Sun Blade", 12000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Sword of Answering", 36000, "legendary", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Talisman of Pure Good", 71680, "legendary", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Talisman of the Sphere", 20000, "legendary", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Talisman of Ultimate Evil", 61440, "legendary", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Tentacle Rod", 5000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Trident of Fish Command", 800, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Universal Solvent", 300, "legendary", 1);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Wand of Binding", 10000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Wand of Enemy Detection", 4000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Wand of Fear", 10000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Wand of Fireballs", 32000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Wand of Lightning Bolts", 32000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Wand of Magic Detection", 1500, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Wand of Magic Missiles", 8000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Wand of Paralysis", 16000, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Wand of Polymorph", 32000, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Wand of Secrets", 1500, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Wand of the War Mage +1", 1200, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Wand of the War Mage +2", 4800, "rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Wand of the War Mage +3", 19200, "very rare", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Wand of Web", 8000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Wind Fan", 1500, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Winged Boots", 8000, "uncommon", 0);
INSERT INTO item_cost (item_name, price, rarity, consumable) VALUES ("Wings of Flying", 5000, "rare", 0);
